/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FightingRouteImport } from './routes/fighting'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemorialRouteImport } from './routes/memorial'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as CirclesIndexRouteImport } from './routes/circles/index'
import { Route as CirclesIdRouteImport } from './routes/circles/$id'
import { Route as PeopleIndexRouteImport } from './routes/people/index'
import { Route as PeopleIdRouteImport } from './routes/people/$id'
import { Route as PeopleMeRouteImport } from './routes/people/me'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesIdRouteImport } from './routes/stories/$id'
import { Route as StoriesNewRouteImport } from './routes/stories/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FightingRoute = FightingRouteImport.update({
  id: '/fighting',
  path: '/fighting',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemorialRoute = MemorialRouteImport.update({
  id: '/memorial',
  path: '/memorial',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIndexRoute = CirclesIndexRouteImport.update({
  id: '/circles/',
  path: '/circles/',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesIdRoute = CirclesIdRouteImport.update({
  id: '/circles/$id',
  path: '/circles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIndexRoute = PeopleIndexRouteImport.update({
  id: '/people/',
  path: '/people/',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleIdRoute = PeopleIdRouteImport.update({
  id: '/people/$id',
  path: '/people/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleMeRoute = PeopleMeRouteImport.update({
  id: '/people/me',
  path: '/people/me',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIdRoute = StoriesIdRouteImport.update({
  id: '/stories/$id',
  path: '/stories/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesNewRoute = StoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fighting': typeof FightingRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/memorial': typeof MemorialRoute
  '/tools': typeof ToolsRoute
  '/circles/$id': typeof CirclesIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/me': typeof PeopleMeRoute
  '/stories/$id': typeof StoriesIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/circles/': typeof CirclesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fighting': typeof FightingRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/memorial': typeof MemorialRoute
  '/tools': typeof ToolsRoute
  '/circles/$id': typeof CirclesIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/me': typeof PeopleMeRoute
  '/stories/$id': typeof StoriesIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/circles': typeof CirclesIndexRoute
  '/people': typeof PeopleIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fighting': typeof FightingRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/memorial': typeof MemorialRoute
  '/tools': typeof ToolsRoute
  '/circles/$id': typeof CirclesIdRoute
  '/people/$id': typeof PeopleIdRoute
  '/people/me': typeof PeopleMeRoute
  '/stories/$id': typeof StoriesIdRoute
  '/stories/new': typeof StoriesNewRoute
  '/circles/': typeof CirclesIndexRoute
  '/people/': typeof PeopleIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fighting'
    | '/guidelines'
    | '/login'
    | '/memorial'
    | '/tools'
    | '/circles/$id'
    | '/people/$id'
    | '/people/me'
    | '/stories/$id'
    | '/stories/new'
    | '/circles/'
    | '/people/'
    | '/stories/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fighting'
    | '/guidelines'
    | '/login'
    | '/memorial'
    | '/tools'
    | '/circles/$id'
    | '/people/$id'
    | '/people/me'
    | '/stories/$id'
    | '/stories/new'
    | '/circles'
    | '/people'
    | '/stories'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/fighting'
    | '/guidelines'
    | '/login'
    | '/memorial'
    | '/tools'
    | '/circles/$id'
    | '/people/$id'
    | '/people/me'
    | '/stories/$id'
    | '/stories/new'
    | '/circles/'
    | '/people/'
    | '/stories/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FightingRoute: typeof FightingRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  MemorialRoute: typeof MemorialRoute
  ToolsRoute: typeof ToolsRoute
  CirclesIdRoute: typeof CirclesIdRoute
  PeopleIdRoute: typeof PeopleIdRoute
  PeopleMeRoute: typeof PeopleMeRoute
  StoriesIdRoute: typeof StoriesIdRoute
  StoriesNewRoute: typeof StoriesNewRoute
  CirclesIndexRoute: typeof CirclesIndexRoute
  PeopleIndexRoute: typeof PeopleIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fighting': {
      id: '/fighting'
      path: '/fighting'
      fullPath: '/fighting'
      preLoaderRoute: typeof FightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memorial': {
      id: '/memorial'
      path: '/memorial'
      fullPath: '/memorial'
      preLoaderRoute: typeof MemorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/': {
      id: '/circles/'
      path: '/circles'
      fullPath: '/circles/'
      preLoaderRoute: typeof CirclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles/$id': {
      id: '/circles/$id'
      path: '/circles/$id'
      fullPath: '/circles/$id'
      preLoaderRoute: typeof CirclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/': {
      id: '/people/'
      path: '/people'
      fullPath: '/people/'
      preLoaderRoute: typeof PeopleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$id': {
      id: '/people/$id'
      path: '/people/$id'
      fullPath: '/people/$id'
      preLoaderRoute: typeof PeopleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/me': {
      id: '/people/me'
      path: '/people/me'
      fullPath: '/people/me'
      preLoaderRoute: typeof PeopleMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$id': {
      id: '/stories/$id'
      path: '/stories/$id'
      fullPath: '/stories/$id'
      preLoaderRoute: typeof StoriesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/new': {
      id: '/stories/new'
      path: '/stories/new'
      fullPath: '/stories/new'
      preLoaderRoute: typeof StoriesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FightingRoute: FightingRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  MemorialRoute: MemorialRoute,
  ToolsRoute: ToolsRoute,
  CirclesIdRoute: CirclesIdRoute,
  PeopleIdRoute: PeopleIdRoute,
  PeopleMeRoute: PeopleMeRoute,
  StoriesIdRoute: StoriesIdRoute,
  StoriesNewRoute: StoriesNewRoute,
  CirclesIndexRoute: CirclesIndexRoute,
  PeopleIndexRoute: PeopleIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
